
services:
  nginx:
    ports:
    - "7500:80"

  node-container:
    build: 
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - "./:/app:ro"
      - "/app/node_modules"
    environment:
      - NOVE_ENV=development
    command: npm run dev