version: '3.8'
services:
  nginx:
      ports:
      - "4500:80"
  node-image:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: raaj
      MONGO_INITDB_ROOT_PASSWORD: raaj@123