version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '4500:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-image:
    build: .
    image: raajspark/node-service
    environment:
      - 'PORT=8500'
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: raaj
      MONGO_INITDB_ROOT_PASSWORD: raaj@123
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
